//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sports.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SportsEntities : DbContext
    {
        public SportsEntities()
            : base("name=SportsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_coach> tbl_coach { get; set; }
        public virtual DbSet<tbl_manager> tbl_manager { get; set; }
        public virtual DbSet<tbl_teams> tbl_teams { get; set; }
        public virtual DbSet<tbl_player> tbl_player { get; set; }
        public virtual DbSet<vw_coach> vw_coach { get; set; }
        public virtual DbSet<vw_manager> vw_manager { get; set; }
    }
}
