//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_player
    {
        public int player_id { get; set; }
        public Nullable<int> manager_id { get; set; }
        public Nullable<int> team_id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public Nullable<int> jersey_no { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }


    }
}
