//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_manager
    {
        public int manager_id { get; set; }
        public string fullname { get; set; }
    }
}
